services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./src/data:/var/www/html/data
      - ./src/js:/var/www/html/js 
      - ./src/style:/var/www/html/style
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: always
